// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIPbBkeoshfEystSCnwI_KNbV75DZ8Asw',
    appId: '1:818246732941:web:0f4059b3aa1f2cd98166c4',
    messagingSenderId: '818246732941',
    projectId: 'ninja-brew-crew-1d228',
    authDomain: 'ninja-brew-crew-1d228.firebaseapp.com',
    storageBucket: 'ninja-brew-crew-1d228.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyLDl2J8mAYF3Mo00M42q9ZMwL2HrPFQA',
    appId: '1:818246732941:android:ce9cc3f3faaae3dc8166c4',
    messagingSenderId: '818246732941',
    projectId: 'ninja-brew-crew-1d228',
    storageBucket: 'ninja-brew-crew-1d228.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ737IhqZRmY3OamXKchpG12MknMN-83c',
    appId: '1:818246732941:ios:52ae76b800cb0dca8166c4',
    messagingSenderId: '818246732941',
    projectId: 'ninja-brew-crew-1d228',
    storageBucket: 'ninja-brew-crew-1d228.appspot.com',
    iosClientId: '818246732941-e3ek9jclfpngfsphj9ooq7u0hugt05ah.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ737IhqZRmY3OamXKchpG12MknMN-83c',
    appId: '1:818246732941:ios:e54c8d541355bf448166c4',
    messagingSenderId: '818246732941',
    projectId: 'ninja-brew-crew-1d228',
    storageBucket: 'ninja-brew-crew-1d228.appspot.com',
    iosClientId: '818246732941-opicvi33evuj6671m7cng2l9lnoadfq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewCrew.RunnerTests',
  );
}
